############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "Contact"
url = "https://www.seafn.org/staff"
weight = 3

[[main]]
name = "Find by"
url = "#"
weight = 3
hasChildren = true

  [[main]]
  parent = "Find by"
  name = "Media Types"
  url = "media_types/"
  weight = 1

  [[main]]
  parent = "Find by"
  name = "Issue Areas"
  url = "issue_areas/"
  weight = 2
  
  [[main]]
  parent = "Find by"
  name = "Ethnic Groups"
  url = "ethnic_groups/"
  weight = 3

# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Contact"
url = "https://www.seafn.org/staff"
weight = 3

