############# English navigation ##############

# main menu
[[main]]
name = "Home"
url = ""
weight = 1

[[main]]
name = "About"
url = "about/"
weight = 2

[[main]]
name = "Contact"
url = "contact/"
weight = 3

[[main]]
name = "Find by"
url = "#"
weight = 3
hasChildren = true

  [[main]]
  parent = "Pages"
  name = "Media Types"
  url = "tags/"
  weight = 1

  [[main]]
  parent = "Pages"
  name = "Issue Areas"
  url = "categories/"
  weight = 2
  
  [[main]]
  parent = "Pages"
  name = "Ethnic Groups"
  url = "ethnicgroups/"
  weight = 3

# footer menu
[[footer]]
name = "Home"
url = "/"
weight = 1

[[footer]]
name = "About"
url = "about/"
weight = 2

[[footer]]
name = "Contact"
url = "contact/"
weight = 3

[[footer]]
name = "Privacy Policy"
url = "privacy-policy/"
weight = 4
